language: pt

pipeline:
- name: SpacyNLP
  model: "pt_core_news_md"
- name: SpacyTokenizer
- name: SpacyFeaturizer
- name: RegexFeaturizer
- name: LexicalSyntacticFeaturizer
- name: CountVectorsFeaturizer
- name: CountVectorsFeaturizer
  analyzer: "char_wb"
  min_ngram: 1
  max_ngram: 4
- name: DIETClassifier
  epochs: 100
  entity_recognition: true
- name: EntitySynonymMapper
- name: ResponseSelector
  epochs: 100
- name: FallbackClassifier
  threshold: 0.3
  ambiguity_threshold: 0.1
assistant_id: 20240929-134311-similar-pouch

policies:
  - name: RulePolicy
    core_fallback_action_name: "action_default_fallback"
    core_fallback_threshold: 0.7
    enable_fallback_prediction: True