language: "pt"
pipeline:
- name: SpacyNLP
  model: "pt_core_news_sm"
- name: SpacyTokenizer
- name: SpacyFeaturizer
- name: LexicalSyntacticFeaturizer
- name: CountVectorsFeaturizer
- name: CountVectorsFeaturizer
  analyzer: "char_wb"
  min_ngram: 1
  max_ngram: 4
- name: DIETClassifier
  epochs: 100
- name: EntitySynonymMapper
- name: ResponseSelector
  epochs: 100
assistant_id: 20240908-141142-furious-seat

policies:
  - name: RulePolicy
    core_fallback_action_name: "action_ask_gemini"
    core_fallback_threshold: 0.2
    enable_fallback_prediction: True
