version: '3.8'

services:
  rasa:
    build: .
    ports:
      - "5005:5005"
    volumes:
      - ./config.yml:/app/config.yml
      - ./domain.yml:/app/domain.yml
      - ./endpoints.yml:/app/endpoints.yml
      - ./data:/app/data
      - ./models:/app/models
    environment:
      - RASA_ENV=production
    depends_on:
      - actions
    # Não sobrescreva o entrypoint
    # entrypoint: []
    command:
      - "rasa"
      - "run"
      - "--model"
      - "models"
      - "--enable-api"
      - "--cors"
      - "*"
      - "--port"
      - "5005"
    restart: "no"

  actions:
    build:
      context: ./actions
      dockerfile: Dockerfile.actions
    ports:
      - "5055:5055"
    volumes:
      - ./actions:/app/actions
    environment:
      - RASA_ENV=production
    # Não sobrescreva o entrypoint
    # entrypoint: []

    command: "python -m rasa_sdk --actions actions --port 5055"
    
